name: KinD Cluster Setup

on:
  pull_request:
    branches:
      - main  

jobs:
  setup-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install KinD
        run: |
          curl -Lo kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
          chmod +x kind
          sudo mv kind /usr/local/bin/

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Create KinD Cluster
        run: |
          cat <<EOF > kind-config.yaml
          kind: Cluster
          apiVersion: kind.x-k8s.io/v1alpha4
          nodes:
            - role: control-plane
            - role: worker
            - role: worker
          EOF
          kind create cluster --config kind-config.yaml

      - name: Wait for Nodes to be Ready
        run: kubectl wait --for=condition=Ready nodes --all --timeout=60s

      - name: Verify Nodes
        run: kubectl get nodes

      - name: Install NGINX Ingress Controller
        run: |
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml

      - name: Wait for Ingress Controller to be Ready
        run: |
          # kubectl wait --namespace ingress-nginx \
          #   --for=condition=ready pod \
          #   --selector=app.kubernetes.io/component=controller \
          #   --timeout=90s
          attempt=1
          max_attempts=5
          until kubectl wait --namespace ingress-nginx --for=condition=ready pod --selector=app.kubernetes.io/component=controller --timeout=90s; do
            if [ $attempt -eq $max_attempts ]; then
              echo "Max attempts reached, giving up"
              exit 1
            fi
            echo "Attempt $attempt failed, waiting to retry..."
            attempt=$((attempt+1))
            sleep 30
          done


      - name: Verify Ingress Controller Deployment
        run: |
          kubectl get pods -n ingress-nginx
      - name: Apply Ingress Configuration
        run: |
          kubectl apply -f k8s/ingress.yaml
          kubectl get ingress


