name: Docker image CI
on:
  pull_request:
    branches:
      - main  
jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set image tag
        id: vars
        run: |
          echo "IMAGE_TAG=1.${{ github.run_number }}" >> $GITHUB_ENV
          

      - name: build image
        run: |
          docker build ./color-generator-be -t samuelekedev/python-api-color-extract:${{ env.IMAGE_TAG }}
          docker build ./img-color-gen-fe -t samuelekedev/devops-color-extractor-frontend:${{ env.IMAGE_TAG }}

      - name: push image to docker hub
        run: |
          docker login -u samuelekedev -p ${{ secrets.DOCKERHUBCI }}
          docker push samuelekedev/python-api-color-extract:${{ env.IMAGE_TAG }}
          docker push samuelekedev/devops-color-extractor-frontend:${{ env.IMAGE_TAG }}
      