name: Docker image CI
on:
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:
  
jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: build image
        run: docker build ./color-generator-be -t samuelekedev/python-api-color-extract:1.1

      - name: push image to docker hub
        run: |
          docker push samuelekedev/python-api-color-extract:1.1
      